//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.12 at 01:41:15 PM IST 
//


package com.invenio.util.aiml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.invenio.chatbot.AIMLClasses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MixedPatternExpressionBot_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "bot");
    private final static QName _MixedTemplateContentContainerSet_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "set");
    private final static QName _MixedTemplateContentContainerThink_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "think");
    private final static QName _MixedTemplateContentContainerSentence_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "sentence");
    private final static QName _MixedTemplateContentContainerLearn_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "learn");
    private final static QName _MixedTemplateContentContainerStar_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "star");
    private final static QName _MixedTemplateContentContainerLowercase_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "lowercase");
    private final static QName _MixedTemplateContentContainerJavascript_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "javascript");
    private final static QName _MixedTemplateContentContainerVersion_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "version");
    private final static QName _MixedTemplateContentContainerSystem_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "system");
    private final static QName _MixedTemplateContentContainerCondition_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "condition");
    private final static QName _MixedTemplateContentContainerSrai_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "srai");
    private final static QName _MixedTemplateContentContainerPerson2_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "person2");
    private final static QName _MixedTemplateContentContainerInput_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "input");
    private final static QName _MixedTemplateContentContainerFormal_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "formal");
    private final static QName _MixedTemplateContentContainerPerson_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "person");
    private final static QName _MixedTemplateContentContainerTopicstar_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "topicstar");
    private final static QName _MixedTemplateContentContainerSize_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "size");
    private final static QName _MixedTemplateContentContainerGossip_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "gossip");
    private final static QName _MixedTemplateContentContainerDate_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "date");
    private final static QName _MixedTemplateContentContainerUppercase_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "uppercase");
    private final static QName _MixedTemplateContentContainerGender_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "gender");
    private final static QName _MixedTemplateContentContainerThat_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "that");
    private final static QName _MixedTemplateContentContainerRandom_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "random");
    private final static QName _MixedTemplateContentContainerGet_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "get");
    private final static QName _MixedTemplateContentContainerThatstar_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "thatstar");
    private final static QName _MixedTemplateContentContainerId_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "id");
    private final static QName _MixedTemplateContentContainerSr_QNAME = new QName("http://alicebot.org/2001/AIML-1.0.1", "sr");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.invenio.chatbot.AIMLClasses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Aiml }
     * 
     */
    public Aiml createAiml() {
        return new Aiml();
    }

    /**
     * Create an instance of {@link MixedTemplateContentContainer }
     * 
     */
    public MixedTemplateContentContainer createMixedTemplateContentContainer() {
        return new MixedTemplateContentContainer();
    }

    /**
     * Create an instance of {@link Aiml.Topic }
     * 
     */
    public Aiml.Topic createAimlTopic() {
        return new Aiml.Topic();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link MixedPatternExpression }
     * 
     */
    public MixedPatternExpression createMixedPatternExpression() {
        return new MixedPatternExpression();
    }

    /**
     * Create an instance of {@link IndexedElement }
     * 
     */
    public IndexedElement createIndexedElement() {
        return new IndexedElement();
    }

    /**
     * Create an instance of {@link BotPredicate }
     * 
     */
    public BotPredicate createBotPredicate() {
        return new BotPredicate();
    }

    /**
     * Create an instance of {@link OneOrTwoDIndexedElement }
     * 
     */
    public OneOrTwoDIndexedElement createOneOrTwoDIndexedElement() {
        return new OneOrTwoDIndexedElement();
    }

    /**
     * Create an instance of {@link MixedTemplateContentContainer.Get }
     * 
     */
    public MixedTemplateContentContainer.Get createMixedTemplateContentContainerGet() {
        return new MixedTemplateContentContainer.Get();
    }

    /**
     * Create an instance of {@link MixedTemplateContentContainer.Condition }
     * 
     */
    public MixedTemplateContentContainer.Condition createMixedTemplateContentContainerCondition() {
        return new MixedTemplateContentContainer.Condition();
    }

    /**
     * Create an instance of {@link MixedTemplateContentContainer.Random }
     * 
     */
    public MixedTemplateContentContainer.Random createMixedTemplateContentContainerRandom() {
        return new MixedTemplateContentContainer.Random();
    }

    /**
     * Create an instance of {@link MixedTemplateContentContainer.Set }
     * 
     */
    public MixedTemplateContentContainer.Set createMixedTemplateContentContainerSet() {
        return new MixedTemplateContentContainer.Set();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BotPredicate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "bot", scope = MixedPatternExpression.class)
    public JAXBElement<BotPredicate> createMixedPatternExpressionBot(BotPredicate value) {
        return new JAXBElement<BotPredicate>(_MixedPatternExpressionBot_QNAME, BotPredicate.class, MixedPatternExpression.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MixedTemplateContentContainer.Set }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "set", scope = MixedTemplateContentContainer.class)
    public JAXBElement<MixedTemplateContentContainer.Set> createMixedTemplateContentContainerSet(MixedTemplateContentContainer.Set value) {
        return new JAXBElement<MixedTemplateContentContainer.Set>(_MixedTemplateContentContainerSet_QNAME, MixedTemplateContentContainer.Set.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MixedTemplateContentContainer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "think", scope = MixedTemplateContentContainer.class)
    public JAXBElement<MixedTemplateContentContainer> createMixedTemplateContentContainerThink(MixedTemplateContentContainer value) {
        return new JAXBElement<MixedTemplateContentContainer>(_MixedTemplateContentContainerThink_QNAME, MixedTemplateContentContainer.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MixedTemplateContentContainer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "sentence", scope = MixedTemplateContentContainer.class)
    public JAXBElement<MixedTemplateContentContainer> createMixedTemplateContentContainerSentence(MixedTemplateContentContainer value) {
        return new JAXBElement<MixedTemplateContentContainer>(_MixedTemplateContentContainerSentence_QNAME, MixedTemplateContentContainer.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "learn", scope = MixedTemplateContentContainer.class)
    public JAXBElement<String> createMixedTemplateContentContainerLearn(String value) {
        return new JAXBElement<String>(_MixedTemplateContentContainerLearn_QNAME, String.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndexedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "star", scope = MixedTemplateContentContainer.class)
    public JAXBElement<IndexedElement> createMixedTemplateContentContainerStar(IndexedElement value) {
        return new JAXBElement<IndexedElement>(_MixedTemplateContentContainerStar_QNAME, IndexedElement.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MixedTemplateContentContainer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "lowercase", scope = MixedTemplateContentContainer.class)
    public JAXBElement<MixedTemplateContentContainer> createMixedTemplateContentContainerLowercase(MixedTemplateContentContainer value) {
        return new JAXBElement<MixedTemplateContentContainer>(_MixedTemplateContentContainerLowercase_QNAME, MixedTemplateContentContainer.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MixedTemplateContentContainer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "javascript", scope = MixedTemplateContentContainer.class)
    public JAXBElement<MixedTemplateContentContainer> createMixedTemplateContentContainerJavascript(MixedTemplateContentContainer value) {
        return new JAXBElement<MixedTemplateContentContainer>(_MixedTemplateContentContainerJavascript_QNAME, MixedTemplateContentContainer.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "version", scope = MixedTemplateContentContainer.class)
    public JAXBElement<Object> createMixedTemplateContentContainerVersion(Object value) {
        return new JAXBElement<Object>(_MixedTemplateContentContainerVersion_QNAME, Object.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MixedTemplateContentContainer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "system", scope = MixedTemplateContentContainer.class)
    public JAXBElement<MixedTemplateContentContainer> createMixedTemplateContentContainerSystem(MixedTemplateContentContainer value) {
        return new JAXBElement<MixedTemplateContentContainer>(_MixedTemplateContentContainerSystem_QNAME, MixedTemplateContentContainer.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MixedTemplateContentContainer.Condition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "condition", scope = MixedTemplateContentContainer.class)
    public JAXBElement<MixedTemplateContentContainer.Condition> createMixedTemplateContentContainerCondition(MixedTemplateContentContainer.Condition value) {
        return new JAXBElement<MixedTemplateContentContainer.Condition>(_MixedTemplateContentContainerCondition_QNAME, MixedTemplateContentContainer.Condition.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MixedTemplateContentContainer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "srai", scope = MixedTemplateContentContainer.class)
    public JAXBElement<MixedTemplateContentContainer> createMixedTemplateContentContainerSrai(MixedTemplateContentContainer value) {
        return new JAXBElement<MixedTemplateContentContainer>(_MixedTemplateContentContainerSrai_QNAME, MixedTemplateContentContainer.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MixedTemplateContentContainer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "person2", scope = MixedTemplateContentContainer.class)
    public JAXBElement<MixedTemplateContentContainer> createMixedTemplateContentContainerPerson2(MixedTemplateContentContainer value) {
        return new JAXBElement<MixedTemplateContentContainer>(_MixedTemplateContentContainerPerson2_QNAME, MixedTemplateContentContainer.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OneOrTwoDIndexedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "input", scope = MixedTemplateContentContainer.class)
    public JAXBElement<OneOrTwoDIndexedElement> createMixedTemplateContentContainerInput(OneOrTwoDIndexedElement value) {
        return new JAXBElement<OneOrTwoDIndexedElement>(_MixedTemplateContentContainerInput_QNAME, OneOrTwoDIndexedElement.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MixedTemplateContentContainer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "formal", scope = MixedTemplateContentContainer.class)
    public JAXBElement<MixedTemplateContentContainer> createMixedTemplateContentContainerFormal(MixedTemplateContentContainer value) {
        return new JAXBElement<MixedTemplateContentContainer>(_MixedTemplateContentContainerFormal_QNAME, MixedTemplateContentContainer.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MixedTemplateContentContainer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "person", scope = MixedTemplateContentContainer.class)
    public JAXBElement<MixedTemplateContentContainer> createMixedTemplateContentContainerPerson(MixedTemplateContentContainer value) {
        return new JAXBElement<MixedTemplateContentContainer>(_MixedTemplateContentContainerPerson_QNAME, MixedTemplateContentContainer.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndexedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "topicstar", scope = MixedTemplateContentContainer.class)
    public JAXBElement<IndexedElement> createMixedTemplateContentContainerTopicstar(IndexedElement value) {
        return new JAXBElement<IndexedElement>(_MixedTemplateContentContainerTopicstar_QNAME, IndexedElement.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "size", scope = MixedTemplateContentContainer.class)
    public JAXBElement<Object> createMixedTemplateContentContainerSize(Object value) {
        return new JAXBElement<Object>(_MixedTemplateContentContainerSize_QNAME, Object.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MixedTemplateContentContainer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "gossip", scope = MixedTemplateContentContainer.class)
    public JAXBElement<MixedTemplateContentContainer> createMixedTemplateContentContainerGossip(MixedTemplateContentContainer value) {
        return new JAXBElement<MixedTemplateContentContainer>(_MixedTemplateContentContainerGossip_QNAME, MixedTemplateContentContainer.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "date", scope = MixedTemplateContentContainer.class)
    public JAXBElement<Object> createMixedTemplateContentContainerDate(Object value) {
        return new JAXBElement<Object>(_MixedTemplateContentContainerDate_QNAME, Object.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MixedTemplateContentContainer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "uppercase", scope = MixedTemplateContentContainer.class)
    public JAXBElement<MixedTemplateContentContainer> createMixedTemplateContentContainerUppercase(MixedTemplateContentContainer value) {
        return new JAXBElement<MixedTemplateContentContainer>(_MixedTemplateContentContainerUppercase_QNAME, MixedTemplateContentContainer.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BotPredicate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "bot", scope = MixedTemplateContentContainer.class)
    public JAXBElement<BotPredicate> createMixedTemplateContentContainerBot(BotPredicate value) {
        return new JAXBElement<BotPredicate>(_MixedPatternExpressionBot_QNAME, BotPredicate.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MixedTemplateContentContainer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "gender", scope = MixedTemplateContentContainer.class)
    public JAXBElement<MixedTemplateContentContainer> createMixedTemplateContentContainerGender(MixedTemplateContentContainer value) {
        return new JAXBElement<MixedTemplateContentContainer>(_MixedTemplateContentContainerGender_QNAME, MixedTemplateContentContainer.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OneOrTwoDIndexedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "that", scope = MixedTemplateContentContainer.class)
    public JAXBElement<OneOrTwoDIndexedElement> createMixedTemplateContentContainerThat(OneOrTwoDIndexedElement value) {
        return new JAXBElement<OneOrTwoDIndexedElement>(_MixedTemplateContentContainerThat_QNAME, OneOrTwoDIndexedElement.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MixedTemplateContentContainer.Random }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "random", scope = MixedTemplateContentContainer.class)
    public JAXBElement<MixedTemplateContentContainer.Random> createMixedTemplateContentContainerRandom(MixedTemplateContentContainer.Random value) {
        return new JAXBElement<MixedTemplateContentContainer.Random>(_MixedTemplateContentContainerRandom_QNAME, MixedTemplateContentContainer.Random.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MixedTemplateContentContainer.Get }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "get", scope = MixedTemplateContentContainer.class)
    public JAXBElement<MixedTemplateContentContainer.Get> createMixedTemplateContentContainerGet(MixedTemplateContentContainer.Get value) {
        return new JAXBElement<MixedTemplateContentContainer.Get>(_MixedTemplateContentContainerGet_QNAME, MixedTemplateContentContainer.Get.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndexedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "thatstar", scope = MixedTemplateContentContainer.class)
    public JAXBElement<IndexedElement> createMixedTemplateContentContainerThatstar(IndexedElement value) {
        return new JAXBElement<IndexedElement>(_MixedTemplateContentContainerThatstar_QNAME, IndexedElement.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "id", scope = MixedTemplateContentContainer.class)
    public JAXBElement<Object> createMixedTemplateContentContainerId(Object value) {
        return new JAXBElement<Object>(_MixedTemplateContentContainerId_QNAME, Object.class, MixedTemplateContentContainer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://alicebot.org/2001/AIML-1.0.1", name = "sr", scope = MixedTemplateContentContainer.class)
    public JAXBElement<Object> createMixedTemplateContentContainerSr(Object value) {
        return new JAXBElement<Object>(_MixedTemplateContentContainerSr_QNAME, Object.class, MixedTemplateContentContainer.class, value);
    }

}
